### ISSUE TITLE
Englobing div

### ISSUE THREAD

**Issue by ghost** [fabriciomendonca/stencil-inline-svg#4]
Hello Fabricio! 
Thanks so much for this, it's really useful. I was wondering if there was a way to avoid the englobing div. A bit like for react the tag <React.Fragment>.
I don't think this is a issue per say but it would be nice to be able to get rid of a non necessary node.
Thanks!
M.

**Comment by fabriciomendonca** [comment]
Hey Marjorie,

I'm really sorry for the delay... :(

Unfortunately, StencilJS has no element like React.Fragment and then you'll need a container to inject the svg content as innerHTML of that container.

On my example I used a `div` tag, but you can use `i`, `span`, `p`...

**Comment by ghost** [comment]
Hi Fabricio,
Thanks for letting me know.
M.
